run:
  timeout: 5m
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - bodyclose
    - nilerr
    - sqlclosecheck
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - whitespace
    - nolintlint
    - prealloc
    - gosec

  disable:
    - wsl
    - gochecknoglobals
    - funlen
    - lll

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
          - "checkPrivateReceivers"
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    excludes:
      - G101

  misspell:
    locale: US

  goimports:
    local-prefixes: git.cscs.ch/openchami

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports"

    - path: _test\.go
      linters:
        - errcheck
      text: "Error return value of .*(Close|Flush)"
