-- TEMPLATE: Initial schema migration for __SERVICE_FULL__
-- Copy this file and replace all __PLACEHOLDER__ markers with your service values.
--
-- Migration: 000001_init
-- Description: Creates the __SCHEMA__ schema and the __RESOURCE_TABLE__ table.

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------

-- TEMPLATE: Each service uses its own PostgreSQL schema for namespace isolation.
CREATE SCHEMA IF NOT EXISTS __SCHEMA__;

-- ---------------------------------------------------------------------------
-- Extensions (require superuser or pre-provisioned in the database)
-- ---------------------------------------------------------------------------

-- UUIDs for primary keys.
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- __RESOURCE_TABLE__ table
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS __SCHEMA__.__RESOURCE_TABLE__ (
    -- Primary key: UUID generated by the database if not provided.
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- TEMPLATE: Add domain-specific columns here.
    name        TEXT        NOT NULL,
    description TEXT        NOT NULL DEFAULT '',

    -- TEMPLATE: Examples of additional column types:
    -- type        TEXT        NOT NULL DEFAULT 'default',
    -- status      TEXT        NOT NULL DEFAULT 'active',
    -- parent_id   UUID        REFERENCES __SCHEMA__.__RESOURCE_TABLE__(id) ON DELETE SET NULL,
    -- tags        JSONB       NOT NULL DEFAULT '{}',
    -- arch        TEXT        NOT NULL DEFAULT 'x86_64',
    -- enabled     BOOLEAN     NOT NULL DEFAULT TRUE,

    -- Audit timestamps.
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- TEMPLATE: Add indexes for columns used in WHERE clauses and JOIN conditions.

-- Unique constraint on name (if names must be unique).
-- TEMPLATE: Remove or adjust this if names are not unique in your service.
CREATE UNIQUE INDEX IF NOT EXISTS idx___RESOURCE_TABLE___name
    ON __SCHEMA__.__RESOURCE_TABLE__ (name);

-- Index for listing ordered by creation time (supports the default ORDER BY).
CREATE INDEX IF NOT EXISTS idx___RESOURCE_TABLE___created_at
    ON __SCHEMA__.__RESOURCE_TABLE__ (created_at DESC);

-- TEMPLATE: Examples of additional indexes:
-- CREATE INDEX IF NOT EXISTS idx___RESOURCE_TABLE___type
--     ON __SCHEMA__.__RESOURCE_TABLE__ (type);
-- CREATE INDEX IF NOT EXISTS idx___RESOURCE_TABLE___parent_id
--     ON __SCHEMA__.__RESOURCE_TABLE__ (parent_id) WHERE parent_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Trigger: auto-update updated_at on row modification
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION __SCHEMA__.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg___RESOURCE_TABLE___updated_at
    BEFORE UPDATE ON __SCHEMA__.__RESOURCE_TABLE__
    FOR EACH ROW
    EXECUTE FUNCTION __SCHEMA__.set_updated_at();
